# Generated by Django 4.0 on 2022-01-10 09:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autopark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)])),
                ('model', models.CharField(max_length=20)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2021)])),
                ('autopark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autopark.autoparkmodel')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
                'db_table': 'cars',
            },
        ),
    ]
